feat: Added very simple individual add-on page
PolarExpress/marketplace-frontend pull request #18
Opened 2024-03-14 13:26 UTC by zebby09

- Added react-router-dom dependency
- Implemented routing to individual add-on page
- Created simple add-on page including:
  -  Name
  - TODO: Author
  - Summary
  - TODO: Install button
  - TODO: ReadMe
- Added a test util to return a store with preloaded mock addons
- Wrote routing tests

2024-03-14 13:53 UTC, Tjalle-S commented on src/style.css
Waarom deze changes? Is dit van Prettier?

2024-03-14 13:55 UTC, Tjalle-S requested changes
I have added a couple of comments. Otherwise, everything seems good.

2024-03-14 13:58 UTC, zebby09 commented on src/style.css
Ja lol, had niet gezien dat ik die ook gecommit had. Zal het ff terugzetten

2024-03-14 14:08 UTC, zebby09 commented on src/pages/AddOnPage.tsx
> +  if (!thisAddOn) {
Is dit goed? `if (thisAddOn === undefined) {`

2024-03-15 09:25 UTC, stickyPiston approved these changes
頑張った！

2024-03-15 09:59 UTC, Tjalle-S approved these changes

2024-03-15 09:59 UTC, merged